server:
  port: 8000

spring:
  profiles:
    active: local    
  jpa:
    hibernate:
      ddl-auto: none      
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5 
  messages:
    basename: i18n/exception
    encoding: UTF-8
  jwt:
    secret: govlepel@$&
    
---

spring:
  profiles: local
  jpa:
    show-sql: true
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl11
    username: secret
    password: secret
    driver-class-name: oracle.jdbc.OracleDriver
  url:
    base: http://localhost:8000

logging:
  level:
    root: warn
    com.rest.api: debug
  
---

spring:
  profiles: dev
  
---

spring:
  profiles: ops
  jpa:
    show-sql: false
  
logging:
  level:
    root: warn
    com.rest.api: info  
  file:
    path: /api/log
    max-history: 7
  
  